### ISSUE TITLE
qt6-examples is qt5 ?

### ISSUE THREAD

**Issue by matti** [torizon/torizon-containers#3]
https://github.com/torizon/torizon-containers/blob/5df5a323755599902ba1b1927ab5cd19b1245b00/debian-docker-images/qt6-wayland-examples/Dockerfile#L7

**Comment by charles2910** [comment]
Hi, @matti.

Thanks for opening the issue! Yeah, that's really wrong on the Dockerfile. We build the images via gitlab CI (`.gitlab-ci.yml`)and pass the build arguments explicitly overriding the default ones declared in the Dockerfiles - so our images are correct, but it was wrong in there. We recently merged in `stable-rc` (see 55268b312bccbdd3cda5676d1fe5e97c391dd5c8) branch some changes and completely removed the default values from the Dockerfiles, so this rotting definition won't be a problem anymore. Soon, we'll merge it in `stable` and make a new release.
