### ISSUE TITLE
Wrong base image in qt6-wayland-examples? 

### ISSUE THREAD

**Issue by ursfassler** [torizon/torizon-containers#5]
The qt**6**-wayland-examples Docker image is based on the qt**5**-wayland Docker image:
https://github.com/torizon/torizon-containers/blob/5df5a323755599902ba1b1927ab5cd19b1245b00/debian-docker-images/qt6-wayland-examples/Dockerfile#L7

This looks like an error, I'd expect that it should be based on the Qt6 image.

**Comment by charles2910** [comment]
Hi, @ursfassler.

Thanks for opening the issue! Yeah, that's really wrong on the Dockerfile. We build the images via gitlab CI (.gitlab-ci.yml)and pass the build arguments explicitly overriding the default ones declared in the Dockerfiles - so our images are correct, but it was wrong in there. We recently merged in stable-rc (see https://github.com/torizon/torizon-containers/commit/55268b312bccbdd3cda5676d1fe5e97c391dd5c8) branch some changes and completely removed the default values from the Dockerfiles, so this rotting definition won't be a problem anymore. Soon, we'll merge it in stable and make a new release.

**Comment by leonheldattoradex** [comment]
I merged `stable-rc` into `stable` now so the fix is on the default branch.

@ursfassler thanks for noticing it, we generally use the release pipeline to build these images and I never noticed the wrong base.
