### ISSUE TITLE
Create a redis container

### ISSUE THREAD

**Issue by escherstair** [torizon/torizon-containers#6]
redis is a common in-memory database widely used in several projects and scenarios.
It would be useful if a redis container would be distributed in the torizon ecosystem.
Do you think this would be possible?

**Comment by charles2910** [comment]
Hi, @escherstair, thanks for filling the bug. These containers we build are specifically to enable hardware acceleration and people to build (graphical) applications on top of it. I think one can use the [redis official container](https://hub.docker.com/_/redis) directly to deploy the database and follow our [documentation on running multiple containers](https://developer.toradex.com/torizon/application-development/working-with-containers/using-multiple-containers-with-torizoncore/).

**Comment by escherstair** [comment]
Hi @charles2910 
thank you.
Only one question: I see that there are several flavors of official redis container. I imagine they start from different OS base images.
Which is the container compatible (or recommended) with the debian used as base by Torizon OS 6?
I would like avoiding useless layers above the debian delivered by Torizon OS,

**Comment by charles2910** [comment]
@escherstair we base our images on `debian:bookworm-slim`, the same as Redis `-bookworm` containers. So choose those ones if you want to make use of layering cache. 

I'm closing this issue for now

**Comment by charles2910** [comment]
If you need more assistance, feel free to drop a question at https://community.toradex.com/

**Comment by microhobby** [comment]
@escherstair we also have a community initiative for common containers: https://github.com/commontorizon/Containerfiles

So, feel free to open your ideas there.
